### ISSUE TITLE
A way to download content from H5P Cornell Notes

### ISSUE THREAD

**Issue by JohnSmith-LT** [otacke/h5p-cornell#21]
Hi Oliver,

I have been playing around with this and really like the concept a lot but I think that it could be even more useful for many users if it had a download to PDF feature. This may be something that other interactions would also benefit from. I wonder if you had ever considered that.

I have been learning H5P development recently and have been working on making a more generic Calendar type and thus I may work on a PDF download function for the Cornell Notes interaction but before I do I was just wondering what your thoughts were? I suppose that I could make it optional for those logged in and appear by default for those not logged in but perhaps just making it available for all is the way to go?

Interested to hear your views.

Regards,

John

**Comment by otacke** [comment]
@JohnSmith-LT There are a couple of features that might improve the content time, for instance allowing more content types that might make sense, change the number of text input fields to not be bound to the Cornell scheme - or some export feature. It's nothing, however, that I'll add in the near future. The content type should be officially released on the H5P Hub first, and at some point I'll have to decide how much I want to give away for free beyond what's available now.

If you want to add something, feel free to create a pull request. It should not be too complicated given that there are a couple of libraries that can help you to export to PDFs. There's probably something that you can use via npm. Just make sure to check the licensing (should be MIT) and to stick to common coding principles and the H5P coding guidelines. I wouldn't even know a scenario where it make sense to restrict an export button to people who are logged into a platform.

**Comment by JohnSmith-LT** [comment]
Cool, thanks @otacke for taking the time to respond. I will add it to my todo list to look at and see what I come up with. It will probably be on the Hub before I get around to doing this anyway.

I agree with your points around restriction - I can't see a good reason for restricting the download, especially if the processing is done client-side. Will probably code it though with the potential for easily adding in the future since it will be no more effort, in case the need arises!
