### ISSUE TITLE
Responsive mode is confusing

### ISSUE THREAD

**Issue by fnoks** [otacke/h5p-cornell#43]
I have gotten several reports from users saying they don't really understand the hiding/showing of the two parts of the Cornell notes (exercise vs notes). Especially if the user has a narrow view, it's very hard to understand they have to click that pencil icon.

I would think always showing these two would make more sense, in combination with making them wrap on smaller screens.

But it's your content type, so you of course decide :)

**Comment by otacke** [comment]
The reason for creating it that way is that you may want to take notes later and want to have more space reading/watching the content first. But if that's something that in practice causes more bad than good, I'll gladly change that.
