### ISSUE TITLE
Copy button

### ISSUE THREAD

**Issue by Joanroa** [otacke/h5p-cornell#63]
When using Cornell Notes, if it's not possible to copy the content to the clipboard, the copy button still appears. Perhaps this shouldn't be there when it's not possible to copy.

**Comment by otacke** [comment]
@Joanroa Could you please leave a report that allows to reproduce this issue? In particular, what browser are you using? What restrictions to `navigator.clipboard` could your platform enforce? Can you share a link to the content in question?

**Comment by otacke** [comment]
Implemented in https://github.com/otacke/h5p-cornell/commit/ca5b7d6ed1ff5dc80dba31819d9251193441ba9d

**Comment by fnoks** [comment]
@otacke : This is relevant when using the iframe embed code cross-domain. It can be overcome by adding "clipboard-write" to the iframe's allow attribute, though, but for all existing embeds that won't help.

**Comment by otacke** [comment]
@fnoks Already done in https://github.com/otacke/h5p-cornell/commit/ca5b7d6ed1ff5dc80dba31819d9251193441ba9d :-D It's a reasonable improvement. I just fear that now people will ask why there's no copy button ...
